# Generated by Django 4.2.2 on 2023-06-20 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_auto_20230620_1713'),
    ]

    operations = [
    ]
